apps/book_reviews/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<book_id>\d+)$', views.book_details, name='book_details'),
    url(r'^users/(?P<user_id>\d+)$', views.user_details, name='user_details'),
    url(r'^add_review/(?P<book_id>\d+)$', views.add_review, name='add_review'),
    url(r'^delete_review/(?P<book_id>\d+)/(?P<review_id>\d+)$', views.delete_review, name='delete_review'),
    url(r'^add', views.add_form, name='add_form'),
    url(r'^create', views.create_review, name='create_review'),
    url(r'^logout', views.logout, name='logout')
]

belt_reviewer/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^books/', include('apps.book_reviews.urls', namespace='books')),
    url(r'^', include('apps.login_registration.urls', namespace='login_registration')),
]

apps/book_reviews/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_registration.models import User

class Author(models.Model):
    name = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # books

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=45)
    author = models.ForeignKey(Author, related_name='books')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #reviews

    def __str__(self):
        return self.title

class Review(models.Model):
    rating = models.IntegerField()
    review_text = models.TextField()
    book = models.ForeignKey(Book, related_name='reviews')
    reviewer = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/book_reviews/views.py
from django.shortcuts import render, redirect
from models import Book, Author, Review
from ..login_registration.models import User
from django.contrib import messages

# Create your views here.
def index(request):
    context = {
        'name': User.objects.get(id=request.session['id']).first_name,
        'reviews': Review.objects.all().order_by('created_at').reverse(),
        'books': Book.objects.all()
    }
    return render(request, 'book_reviews/index.html', context)

def logout(request):
    request.session.pop('id')
    return redirect('login_registration:index')

def add_form(request):
    return render(request, 'book_reviews/add.html', {'authors': Author.objects.all()})

def create_review(request):
    errors = []
    if len(request.POST['title']) < 1:
        errors.append("Title cannot be blank.")
    if request.POST['author_list'] == '':
        if request.POST['add_author'] == '':
            errors.append("Author cannot be blank.")
        else:
            author_name = request.POST['add_author']
    else:
        author_name = request.POST['author_list']
    if len(request.POST['review']) < 1:
        errors.append("Review cannot be blank.")
    for err in errors:
        messages.add_message(request, messages.ERROR, err)
    if errors:
        return redirect('books:add_form')
    if not Author.objects.filter(name=author_name):
        Author.objects.create(name=author_name)
    try:
        request.session['book_id'] = Book.objects.get(title=request.POST['title'], author=Author.objects.get(name=author_name)).id
    except:
        request.session['book_id'] = Book.objects.create(title=request.POST['title'], author=Author.objects.get(name=author_name)).id # create Book, if none
    Review.objects.create(rating=request.POST['rating'], review_text=request.POST['review'], book=Book.objects.get(id=request.session['book_id']), reviewer=User.objects.get(id=request.session['id'])) # create Review, if none
    print request.session['book_id'], "<<<-------- request.session['book_id']"
    return redirect('books:book_details', book_id=request.session['book_id'])

def add_review(request, book_id):
    Review.objects.create(rating=request.POST['rating'], review_text=request.POST['review'], book=Book.objects.get(id=book_id), reviewer=User.objects.get(id=request.session['id']))
    request.session['book_id'] = book_id
    return redirect('books:book_details', book_id=request.session['book_id'])

def book_details(request, book_id):
    context = {
        'book': Book.objects.get(id=book_id),
        'reviews': Review.objects.filter(book=book_id)
    }
    return render(request, 'book_reviews/book_details.html', context)

def user_details(request, user_id):
    context = {
        'user': User.objects.filter(id=user_id)[0],
        'reviewed_books': Book.objects.filter(reviews__reviewer=user_id),
        'num_reviews': Review.objects.filter(reviewer=user_id).count()
    }
    return render(request, 'book_reviews/user_details.html', context)

def delete_review(request, book_id, review_id):
    if request.method == 'POST':
        Review.objects.filter(id=review_id).delete()
    return redirect('books:book_details', book_id=book_id)

apps/book_reviews/templates/book_reviews/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Book and Review</title>
  </head>
  <body>
    <div class="header">
      <a href="{% url 'books:index' %}">Home</a>
      <a href="{% url 'books:logout' %}">Logout</a>
    </div>
    <h2>Add a New Book Title and a Review:</h2>
    <form class="" action="{% url 'books:create_review' %}" method="post">
      {% csrf_token %}
      <label for="title">Book Title:</label>
      <input type="text" name="title" value="">
      <br>
      <label for="author">Author:</label>
      <div name="author">
        <label for="author_list">Choose from the list:</label>
        <select class="" name="author_list">
            <option value="James Patterson">James Patterson</option>
            <option value="J.K. Rowling">J.K. Rowling</option>
            <option value="Stephen King">Stephen King</option>
            <option value="Mark Twain">Mark Twain</option>
            <option value="William Shakespeare">William Shakespeare</option>
            <option value="Dr. Seuss">Dr. Seuss</option>
            <option value=""></option>
          {% for author in authors %}
            <option value="{{ author }}">{{ author }}</option>
          {% endfor %}
        </select>
      <label for="add_author">Or add a new author:</label>
      <input type="text" name="add_author" value="">
      </div>
      <label for="review">Review:</label>
      <textarea name="review" rows="8" cols="80"></textarea>
      <select class="" name="rating">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
      <label for="rating">stars</label>
      <input type="submit" name="" value="Add book and review">
    </form>
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </body>
</html>

apps/book_reviews/templates/book_reviews/book_details.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Book and Review</title>
  </head>
  <body>
    <div class="header">
      <a href="{% url 'books:index' %}">Home</a>
      <a href="{% url 'books:logout' %}">Logout</a>
    </div>
  <div class="left_side">
    <h1>{{ book.title }}</h1>
    <h3>Author: {{ book.author }}</h3>
      <h2>Reviews:</h2>
      {% for review in reviews|slice:":3" %}
        <p>
          Rating:
          {% with ''|center:review.rating as range %}
            {% for _ in range %}<img src="" alt="*">{% endfor %}
          {% endwith %}
        </p>
        <p>
          <a href="/books/users/{{ review.reviewer.id }}">{{ review.reviewer.first_name }}</a>
          says: {{ review.review_text }}
        </p>
        <p>posted on {{ review.created_at }}</p>
        {% if review.reviewer.id == request.session.id %}
          <form action="{% url 'books:delete_review' review_id=review.id book_id=book.id %}" method="post">
            {% csrf_token %}
            <input type="submit" name="" value="Delete review">
          </form>
        {% endif %}
      {% endfor %}
    </div>
    <form class="" action="{% url 'books:add_review' book_id=book.id %}" method="post">
      {% csrf_token %}
      <label for="review">Add a review:</label>
      <textarea name="review" rows="8" cols="80"></textarea>
      <select class="" name="rating">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
      <label for="rating">stars</label>
      <input type="submit" name="" value="Submit review">
    </form>
  </body>
</html>

apps/book_reviews/templates/book_reviews/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <title>Book Reviews</title>
  </head>
  <body>
    <div class="header">
      <h1>Welcome, {{ name }}!</h1>
      <a href="{% url 'books:add_form' %}">Add Book and Review</a>
      <a href="{% url 'books:logout' %}">Logout</a>
    </div>
    <div class="left_side">
      <h2>Recent Book Reviews:</h2>
      {% if reviews %}
        {% for review in reviews|slice:":3" %}
          <a href="{% url 'books:book_details' book_id=review.book.id %}">{{ review.book.title }}</a>
          <p>Rating: {% with ''|center:review.rating as range %}{% for _ in range %}<img src="{% static 'book_reviews/images/imdb_star_22x21-2889147855._CB522736550_.png' %}" alt="*">{% endfor %}{% endwith %}</p>
          <p><a href="{% url 'books:user_details' user_id=review.reviewer.id %}">{{ review.reviewer.first_name }}</a> says: {{ review.review_text }}</p>
          <p>posted on {{ review.created_at }}</p>
        {% endfor %}
      {% endif %}
    </div>
    <div class="books_with_reviews">
      <h2>Other books with reviews:</h2>
      {% for book in books %}
        <p><a href="{% url 'books:book_details' book_id=book.id %}">{{ book }}</a></p>
      {% endfor %}
    </div>
  </body>
</html>

apps/book_reviews/templates/book_reviews/user_details.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Reviews</title>
  </head>
  <body>
    <div class="header">
      <a href="{% url 'books:index' %}">Home</a>
      <a href="{% url 'books:add_form' %}">Add Book and Review</a>
      <a href="{% url 'books:logout' %}">Logout</a>
    </div>
    <h2>User Alias: {{ user.first_name }}</h2>
    <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Total Reviews: {{ num_reviews }}</p>
    <p>Posted Reviews on the following books:</p>
    {% for book in reviewed_books %}
    <p><a href="{% url 'books:book_details' book_id=book.id %}">{{ book }}</a></p>
    {% endfor %}
  </body>
</html>